language: c

before_install:
  # cleanup git stuff (source format 1.0 does not exclude it)
  - rm -rf .git .travis.yml
  # update package list
  - sudo apt-get update -qq
  # remove the shiped gawk (we use mawk)
  - sudo apt-get purge -qq gawk
  #
  - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl libcrypt-ssleay-perl && uscan --force-download && sudo apt-get purge -qq libwww-perl libcrypt-ssleay-perl && sudo apt-get autoremove -qq
#  # installneeded packages for uscan
#  - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl libcrypt-ssleay-perl
#  # download original tarball
#  - uscan --force-download
#  # remove packages needed for uscan
#  - sudo apt-get purge -qq libwww-perl libcrypt-ssleay-perl
#  - sudo apt-get autoremove -qq

install:
  # install implicit build dependencies
  - sudo apt-get install -qq --no-install-recommends build-essential fakeroot devscripts
  # add ppa for libfreeradius-client-dev and newer lintian
  - sudo add-apt-repository -y ppa:waja/precise-backports
  - sudo apt-get update -qq
  # install explicit build dependencies
  - sudo apt-get install -qq --no-install-recommends debhelper dpatch perl autotools-dev libdbi-dev libldap2-dev libpq-dev libmysqlclient-dev libfreeradius-client-dev libkrb5-dev libnet-snmp-perl procps mawk dpatch hardening-wrapper

script:
    # build the debian package
    - debuild -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false

