language: c

before_install:
  # cleanup git stuff (source format 1.0 does not exclude it)
  - rm -rf .git .travis.yml
  # update package list
  - sudo apt-get update -qq
  #
  - if [ "$TRAVIS_BRANCH" != "m-p" ]; then sudo apt-get install -qq --no-install-recommends devscripts libwww-perl libcrypt-ssleay-perl && uscan --force-download && sudo apt-get purge -qq libwww-perl libcrypt-ssleay-perl && sudo apt-get autoremove -qq; else sudo apt-get install -qq --no-install-recommends devscripts && VER=$(head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'); wget https://gist.githubusercontent.com/waja/9142217/raw/git2release -O /tmp/git2release && sh /tmp/git2release --release-tarball https://github.com/monitoring-plugins/monitoring-plugins/archive/master.tar.gz && mv monitoring-plugins*.tar.gz .. && sh /tmp/git2release --prepare-debian ../monitoring-plugins-1.5.tar.gz && tar -xzf ../monitoring-plugins_${VER}.orig.tar.gz -C ../ && cp -a debian ../monitoring-plugins-${VER}/ && cd ../monitoring-plugins-${VER}/; fi
#  # installneeded packages for uscan
#  - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl libcrypt-ssleay-perl
#  # download original tarball
#  - uscan --force-download
#  # remove packages needed for uscan
#  - sudo apt-get purge -qq libwww-perl libcrypt-ssleay-perl
#  - sudo apt-get autoremove -qq

install:
  # install implicit build dependencies
  - sudo apt-get install -qq --no-install-recommends build-essential fakeroot devscripts
  # install explicit build dependencies
  - sudo apt-get install -qq --no-install-recommends debhelper dpatch perl autotools-dev libdbi-dev libldap2-dev libpq-dev libmysqlclient-dev libradiusclient-ng-dev libkrb5-dev libnet-snmp-perl procps mawk dpatch hardening-wrapper

script:
    # build the debian package
    - debuild -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false

